# Generated by Django 5.0.7 on 2024-07-29 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='css_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='html_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='js_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
